- hosts: localhost
  tasks:
  - name: install git
    become: yes
    become_method: sudo
    yum: name=git state=latest
  - name: clone petclinic
    git:
     repo: https://github.com/sslakmon/ciscocd.git
     dest: /home/ec2-user/ciscocd/
     update: no
  - name: clone cisocd
    git:
     repo: https://github.com/sslakmon/spring-petclinic.git 
     dest: /home/ec2-user/petclinic/
     update: no
#  - name: download maven
#    unarchive:
#     src: http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
#     dest: /home/ec2-user/
#     remote_src: True
  - name: install docker
    become: yes
    become_method: sudo
    yum: name=docker state=latest
  - name: add user to group
    become: yes
    become_method: sudo
    user:
     name: ec2-user
     group: docker
     append: yes
  - name: start the docker service
    become: yes
    become_method: sudo
    service:
      name: docker
      state: started

    
