FROM centos
RUN yum install -y wget 
RUN wget http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
RUN gunzip apache-maven-3.3.9-bin.tar.gz 
RUN tar -xvf apache-maven-3.3.9-bin.tar
